### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by leejw51crypto** [tharsis/ethermint#31] opened 2021-05-19 12:37 UTC
when i run `make` , cannot proceeed
```
make
Installing stringer...
Installing go-bindata...
no required module provides package github.com/kevinburke/go-bindata/go-bindata; to add it:
	go get github.com/kevinburke/go-bindata/go-bindata
make: *** [Makefile:196: contract-tools] 오류 1
```
os: ubuntu 21
go: go version go1.16.4 linux/amd64

`make build` working fine
`make test` ,too

**Comment by fedekunze** [comment] 2021-05-20 07:46
thanks @leejw51crypto, I couldn't reproduce your error but got this one instead:

```
make: *** No rule to make target `verify', needed by `all'.  Stop.
```

Which I fixed in #33. Let me know if it works for you

**Closed** 2021-05-21 10:24 UTC
